title: "Kush Blog"

social_links:
  - name: GitHub
    url: "https://github.com/Kush-Singh-26"

# baseurl: "/blogs" # If hosted in a subdirectory
# url: "https://kush-singh-26.github.io" # Change this to your actual site URL
github_username: Kush-Singh-26

# Theme settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

favicon: "/favicon.ico"
head:
  custom: "<link rel='icon' type='image/x-icon' href='/favicon.ico'>"

minima:
  skin: dark
