title: "Kush Blogs"

remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme 
- jekyll-feed

minima:
  skin: 'dark'

markdown: kramdown

permalink: /:year/:month/:day/:title/
collections:
  posts:
    output: true
baseurl: "/blogs"
